

# TODO Altitude of ground
ALTITUDE_GROUND = -82.5     # [m]

# IM920 ID
IM920_ID_PARENT = "37B6"
IM920_ID_CHILD = "2785"
IM920_ID_CONTROL = "1CD2"

ADDR_IM920_PARENT = (IM920_ID_PARENT,)
ADDR_IM920_CHILD = (IM920_ID_CHILD,)
ADDR_IM920_CONTROL = (IM920_ID_CONTROL,)

# Command Setting
COMMAND_START = b"ST"
COMMAND_STOP = b"SP"
COMMAND_REGISTER_STATE = b"GS"
COMMAND_REQUEST_DATA = b"RD"
COMMAND_REQUEST_STATE = b"RS"

# Encoding
ENCODING_IM920 = "hex_codec"
